# Generated by Django 5.0.3 on 2024-07-18 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='skills',
            new_name='Skill',
        ),
    ]
