# Generated by Django 5.0.3 on 2024-07-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_rename_skills_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
